hwdec=auto-copy
no-border
window-corners=round
keep-open=yes
save-position-on-quit=yes
audio-file-auto=fuzzy
sub-auto=fuzzy
gpu-shader-cache-dir="~~/cache/shaders_cache"
watch-later-dir="~~/cache/watch_later"
