import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = {family = "CaskaydiaCoveNerdFont", style = "Regular"}
size = 11

[window]
padding = { x = 8, y = 5 }
decorations = "Full"
opacity = 0.9
blur = false

[cursor]
vi_mode_style = { shape = "Block", blinking = "On" }

[terminal]
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
{ key = "v", mods = "Control", action = "Paste" },
{ key = "b", mods = "Control", action = "ToggleViMode"}
]
