# set -g default-terminal screen-256color # better compability
set -g default-terminal tmux-256color # better effect
set -as terminal-features ',alacritty*:RGB'
set -as terminal-features ',xterm-*:RGB'
set -as terminal-features ',gnome*:RGB'

# bindings
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux'

# mouse support
set -g mouse

# catppuccin configure
# window prompt

set -g @catppuccin_status_background "none"
set -g @catppuccin_window_status_style "custom"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_left_separator "#[bg=default,fg=#{@thm_overlay_2}]█#[bg=#{@thm_overlay_2},fg=#{@thm_surface_0}]"
set -g @catppuccin_window_middle_separator "#[fg=#{@thm_overlay_2}]█"
set -g @catppuccin_window_right_separator "#[bg=default,fg=#{@thm_surface_0}]█"
set -g @catppuccin_window_current_left_separator "#[bg=default,fg=#{@thm_mauve}]█#[bg=#{@thm_mauve},fg=#{@thm_bg}]"
set -g @catppuccin_window_current_middle_separator "#[fg=#{@thm_mauve}]█"
set -g @catppuccin_window_current_right_separator "#[bg=default,fg=#{@thm_surface_1}]█"

set -g status-position top
set -g status-justify "absolute-centre"
set -g window-status-separator " "
set -g status-left-length 0
set -g status-left "#[fg=#{@thm_fg} bold] [#S] "
set -ga status-left "#{?client_prefix,#[fg=#{@thm_red} bold]PREFIX ,#{?#{==:#{pane_mode},copy-mode},#[fg=#{@thm_yellow} bold]COPY ,#[fg=#{@thm_green} bold]NORMAL }}"
set -g status-right "#{E:@catppuccin_status_date_time}"

# tmux navigate when there is no plugins
# bind -n c-h select-pane -L
# bind -n c-j select-pane -D
# bind -n c-k select-pane -U
# bind -n c-l select-pane -R
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'


set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-q send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

unbind %   # split-window -h
unbind '"' # split-window
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Rename session and window
unbind "\$" # rename-session
unbind ,    # rename-window
bind r command-prompt -I "#{window_name}" "rename-window '%%'"
bind R command-prompt -I "#{session_name}" "rename-session '%%'"

# Kill pane/window/session shortcuts
unbind & # kill-window
bind x confirm-before -p "kill-pane #P? (y/n)" kill-pane
bind X confirm-before -p "kill-window #W? (y/n)" kill-window
bind C-x confirm-before -p "kill other windows? (y/n)" "kill-window -a"
bind q confirm-before -p "kill-session #S? (y/n)" kill-session

# Hide status bar on demand
bind C-s if -F '#{s/off//:status}' 'set status off' 'set status on'

set -sg escape-time 50
# don't show escape sequence when startup
run '~/.tmux/plugins/tpm/tpm'

set -gF message-style 'fg=#{@thm_teal},bg=default,fill=#{@thm_bg}'
set -gF message-command-style 'fg=#{@thm_teal},bg=default,fill=#{@thm_bg}'
set -g copy-mode-line-numbers off

# tmux osc52 support configuration
set -s set-clipboard on
