# set -g default-terminal screen-256color # better compability
set -g default-terminal tmux-256color # better effect
set-option -ga terminal-overrides ",alacritty*:RGB,xterm-*:RGB,gnome*:RGB"

# bindings
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux'

# mouse support
# set -g mouse

# catppuccin configure
# window prompt

set -g @catppuccin_window_number_position "left"
set -g @catppuccin_window_current_number_color "#{@thm_green}"
set -g @catppuccin_window_text ""
set -g @catppuccin_window_number "#[bold]Tab ###I "
set -g @catppuccin_window_current_text ""
set -g @catppuccin_window_current_number "#[bold]Tab ###I "
set -g @catppuccin_window_status_style "custom"
set -g @catppuccin_window_right_separator "#[fg=#{@_ctp_status_bg},reverse]#[none]"

set -g @catppuccin_window_left_separator "#[fg=#{@_ctp_status_bg}] #[none]"
set -g @catppuccin_window_middle_separator "#[bg=#{@catppuccin_window_text_color},fg=#{@catppuccin_window_number_color}]"
set -g @catppuccin_window_current_middle_separator "#[bg=#{@catppuccin_window_current_text_color},fg=#{@catppuccin_window_current_number_color}]"

# Run plugin
run ~/projects/catppuccin-tmux/catppuccin.tmux

set -g window-status-separator ""
set -g status-left-length 0
set -g status-left "#[fg=#{@thm_fg} bold](#S) "
set -ga status-left "#{?client_prefix,#[fg=#{@thm_red} bold]PREFIX ,#{?#{==:#{pane_mode},copy-mode},#[fg=#{@thm_yellow} bold]COPY ,#[fg=#{@thm_green} bold]NORMAL }}"
set -g status-right ""

# tmux navigate when there is no plugins
# bind -n c-h select-pane -L
# bind -n c-j select-pane -D
# bind -n c-k select-pane -U
# bind -n c-l select-pane -R
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'


set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

unbind %   # split-window -h
unbind '"' # split-window
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# monitor-activity
bind M set-option -p monitor-activity

# rename window right after it's created
set-hook -g after-new-window 'command-prompt -I "#{window_name}" "rename-window '%%'"'

# Rename session and window
unbind "\$" # rename-session
unbind ,    # rename-window
bind r command-prompt -I "#{window_name}" "rename-window '%%'"
bind R command-prompt -I "#{session_name}" "rename-session '%%'"

# Kill pane/window/session shortcuts
unbind & # kill-window
bind x confirm-before -p "kill-pane #P? (y/n)" kill-pane
bind X confirm-before -p "kill-window #W? (y/n)" kill-window
bind C-x confirm-before -p "kill other windows? (y/n)" "kill-window -a"
bind q confirm-before -p "kill-session #S? (y/n)" kill-session

# Hide status bar on demand
bind C-s if -F '#{s/off//:status}' 'set status off' 'set status on'

set -sg escape-time 50
# don't show escape sequence when startup
run '~/.tmux/plugins/tpm/tpm'

# tmux osc52 support configuration
set -s set-clipboard on
