hwdec=auto-copy
no-border
{{- if eq .chezmoi.os "windows" }}
window-corners=round
{{- end }}
keep-open=yes
save-position-on-quit=yes
audio-file-auto=fuzzy
sub-auto=fuzzy
gpu-shader-cache-dir="~~/cache/shaders_cache"
watch-later-dir="~~/cache/watch_later"
