alias vim=nvim
alias vi=nvim
alias fd=fdfind
alias bat=batcat
alias ls='exa'
alias ll='exa -al'
alias la='exa -a'
alias l='exa -l'
# alias ii='/mnt/c/Windows/explorer.exe'
# alias wclip='/mnt/c/Windows/system32/clip.exe'
# alias code="/mnt/c/Users/fade/AppData/Local/Programs/Microsoft\ VS\ Code/bin/code"
# alias wcopy="/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe -Command gcb"
